### ISSUE TITLE
Does not install properly on ST3+W8

### ISSUE THREAD

**Issue by z-m-k** [jarhart/SublimeSBT#19]
On install I get in the console:

``` python
Traceback (most recent call last):
  File "errormarker in \Apps\Sublime Text\Data\Installed Packages\SublimeSBT.sublime-package", line 28, in mark_errors_in
  File "errormarker in \Apps\Sublime Text\Data\Installed Packages\SublimeSBT.sublime-package", line 57, in _mark_errors_in_view
  File "errormarker in \Apps\Sublime Text\Data\Installed Packages\SublimeSBT.sublime-package", line 78, in _highlighter
  File "highlighter in \Apps\Sublime Text\Data\Installed Packages\SublimeSBT.sublime-package", line 18, in __init__
  File "highlighter in \Apps\Sublime Text\Data\Installed Packages\SublimeSBT.sublime-package", line 95, in _update_highlight_args
  File "highlighter in \Apps\Sublime Text\Data\Installed Packages\SublimeSBT.sublime-package", line 101, in _create_highlight_args
TypeError: 'NoneType' object is not subscriptable
```

After this, none of the commands show up in the palette.

**Comment by boonedox** [comment]
I'm getting similar behavior, except that "SBT: Clear History" is the only command showing up.  I see the same error in the console when I install or enable the package.  I'm running ST3, build 3065.  I've got a scala file in the directory as well as .sbt.

**Comment by ouinon** [comment]
Getting exactly the same problem as @boonedox. Here's the [output](https://gist.github.com/ouinon/8ad6cc1b7e314ce7e248) from the installation:

**Comment by inkytonik** [comment]
I don't have a W8 machine to try on but perhaps we can investigate together. Most of the crashes are in the following code from sbtsettings.py (line 55 is the second line):

    def _view_settings(self):
        for view in maybe(self.window.active_view()):
            return view.settings().get('SublimeSBT', {})
        return {}

It seems strange for this to be going wrong, so probably the first thing to do is to print some stuff out to see things in more detail. If you're up for poking around, try inserting (untested):

    print ('window: ' + str(self.window))
    print ('active_view: ' + str(self.window.active_view()))

Reload and see what happens.
